/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DocxtemplaterImport } from './routes/docxtemplater'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DocxtemplaterRoute = DocxtemplaterImport.update({
  id: '/docxtemplater',
  path: '/docxtemplater',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/docxtemplater': {
      id: '/docxtemplater'
      path: '/docxtemplater'
      fullPath: '/docxtemplater'
      preLoaderRoute: typeof DocxtemplaterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docxtemplater': typeof DocxtemplaterRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docxtemplater': typeof DocxtemplaterRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/docxtemplater': typeof DocxtemplaterRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docxtemplater'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docxtemplater'
  id: '__root__' | '/' | '/docxtemplater'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocxtemplaterRoute: typeof DocxtemplaterRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocxtemplaterRoute: DocxtemplaterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/docxtemplater"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/docxtemplater": {
      "filePath": "docxtemplater.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
